version: '2.4'
services:
  nginx-proxy:
    image: hasnat/nginx-proxy
    build: .
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "${EX_SSL_CERTS_LOCATION:-./container-data/nginx-proxy/certs}:/etc/nginx/certs"

  whoami:
    container_name: whoami
    image: jwilder/whoami
    environment:
      - "VIRTUAL_HOST=whoami.127.0.0.1.nip.io"
      - "VIRTUAL_PORT=8000"
      - "VHOST_ACCESS_LOG=access_log /dev/stdout headers_log;"

  whoami-vts:
    container_name: whoami-vts
    image: jwilder/whoami
    environment:
      - "VIRTUAL_HOST=whoami-vts.127.0.0.1.nip.io"
      - "VIRTUAL_PORT=8000"
      - "VHOST_ACCESS_LOG=access_log /dev/stdout headers_log;"
      - "VHOST_VTS_ENABLE=true"
      - "VHOST_VTS_CONF=location /status/format/prometheus { vhost_traffic_status_display; vhost_traffic_status_display_format prometheus; }"

  whoami-ssl:
    container_name: whoami-ssl
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami-ssl.local.example.com
      - VIRTUAL_PORT=8000
      - "VHOST_ACCESS_LOG=access_log /dev/stdout headers_log;"


  whoami-password:
    container_name: whoami-password
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=password.127.0.0.1.nip.io
      - VIRTUAL_PORT=8000
      - VHOST_HTPASSWD_PLAIN=admin:admin;test:test


  whoami-multi:
    container_name: whoami-multi
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=multi-host-1.127.0.0.1.nip.io,multi-host-2.127.0.0.1.nip.io
      - VIRTUAL_PORT=8000
