version: '2.4'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    build: .
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "${A4G_SSL_CERTS_LOCATION}:/etc/nginx/certs"


  whoami:
    container_name: whoami
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.127.0.0.1.xip.io
      - VIRTUAL_PORT=8000
      - VHOST_ACCESS_LOG=access_log /dev/stdout headers_log;

  whoami-ssl:
    container_name: whoami-ssl
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami-ssl.local.a4g.com
      - VIRTUAL_PORT=8000
      - VHOST_ACCESS_LOG=access_log /dev/stdout headers_log;


  whoami-password:
    container_name: whoami-password
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=password.127.0.0.1.xip.io
      - VIRTUAL_PORT=8000
      - VHOST_HTPASSWD_PLAIN=admin:admin;test:test
      - "VHOST_HTPASSWD=admin1:$$apr1$$C4yah1XV$$YSZ5x5xEEbieYbYfpnQRv/;test1:$$apr1$$yP1tWxNz$$SyhZnvAzH2RbxjBaHKDP5."
