load_module /etc/nginx/modules/ngx_http_ssl_ja3_module.so;
load_module /etc/nginx/modules/ngx_stream_ssl_ja3_preread_module.so;
load_module /etc/nginx/modules/ngx_http_js_module.so;
load_module /etc/nginx/modules/ngx_http_headers_more_filter_module.so;
load_module /etc/nginx/modules/ngx_http_vhost_traffic_status_module.so;

user  www-data;
worker_processes  auto;

error_log  stderr warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    js_include /njs/logger/logger.js;


    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$host - $remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /dev/stdout  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    gzip  on;
    vhost_traffic_status_zone;
    ### templating will run and update this file which includes vhosts, this is placeholder on first boot
}
daemon off;